#
# Travis CI recipe to build docker image.
#

sudo: required

language: generic

services:
  - docker

script:
  - echo "Starting build of Docker image..."
#  - docker build --no-cache --pull --file debian.dockerfile -t oracle-java-8:debian .
#  - docker build --no-cache --pull --file ubuntu16.dockerfile -t oracle-java-8:ubuntu16 .
#  - docker build --no-cache --pull --file phusion.dockerfile -t oracle-java-8:phusion .
#  - docker build --no-cache --pull --file ubuntu18.dockerfile -t oracle-java-8:ubuntu18 .
#  - docker build --no-cache --pull -t $TRAVIS_REPO_SLUG:$TRAVIS_JOB_ID .