_phusion:
			docker build -f phusion.Dockerfile   -t f0nzie/oracle-java-8:phusion .
_ubuntu14:
			docker build -f ubuntu14.Dockerfile  -t f0nzie/oracle-java-8:ubuntu14 .			
_ubuntu16:
			docker build -f ubuntu16.Dockerfile  -t f0nzie/oracle-java-8:ubuntu16 .
_ubuntu18:
			docker build -f ubuntu18.Dockerfile  -t f0nzie/oracle-java-8:ubuntu18 .
_debian9:
			docker build -f debian9.Dockerfile   -t f0nzie/oracle-java-8:debian9 .			
_debian10:
			docker build -f debian10.Dockerfile  -t f0nzie/oracle-java-8:debian10 .

